# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernameValid', '0002_auto_20170523_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testing',
            new_name='User',
        ),
    ]
